name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
exclude-contributors:
  - dependabot
  - renovate
categories:
  - title: '⚡️ Breaking Changes'
    when:
      label: breaking
  - title: '🚀 Features'
    when:
      labels:
        - feature
        - enhancement
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - bug
        - fix
  - title: '🔨 Maintenance'
    when:
      labels:
        - chore
        - refactor
  - title: '📦 Dependencies'
    when:
      label: dependencies
  - title: '⚙️ CI/CD'
    when:
      label: github_actions
  - title: '🧪 Samples'
    when:
      labels:
        - samples
        - owin
  - title: '📝 Documentation'
    when:
      label: documentation
  - title: Misc
    when:
      label: '*'
  - type: pre-exclude
    when:
      label: ignore-for-release
  - type: version-resolver
    semver-increment: major
    when:
      label: breaking
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - feature
        - enhancement
  - type: version-resolver
    semver-increment: patch
    when:
      labels:
        - bug
        - fix
        - refactor
  - type: version-resolver
    semver-increment: patch
prerelease-identifier: rc
template: |
  ## Changes
  $CHANGES
