minimumReleaseAgeExclude:
  - vite@8.0.16
  - react-dom@19.2.7
  - react@19.2.7

onlyBuiltDependencies:
  - esbuild

overrides:
  react-router: '^8.3.0'
  brace-expansion: '^5.0.8'
  '@remix-run/router': '^1.23.2'
