minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - '@types/react@19.2.15'

onlyBuiltDependencies:
  - esbuild

overrides:
  react-router: "^6.30.3"
  "@remix-run/router": "^1.23.2"

peerDependencyRules:
  allowedVersions:
    eslint: "10"
