services:

  dotnet:
    build: .
    image: dotnet-sdk
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}
        target: /workspace
        consistency: cached
    command: sleep infinity

  keycloak:
    build: ./keycloak
    image: keycloak:cas
    environment:
      # https://www.keycloak.org/server/configuration
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/reverseproxy
      KC_PROXY_HEADERS: xforwarded
      # https://www.keycloak.org/server/all-config
      KC_HOSTNAME: auth.dev.local
      KC_HTTPS_CERTIFICATE_FILE: /run/secrets/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /run/secrets/key.pem
    volumes:
      - type: volume
        source: keycloak_data
        target: /opt/keycloak/data
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/keycloak/export
        target: /opt/keycloak/data/export
        bind:
          create_host_path: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/keycloak/import
        target: /opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - 127.0.0.1:8443:8443
    secrets:
      - cert.pem
      - key.pem
    networks:
      default:
        aliases:
          - auth.dev.local

  redis:
    # https://hub.docker.com/_/redis
    image: redis
    volumes:
      - type: volume
        source: redis_data
        target: /data
    ports:
      - 127.0.0.1:6379:6379

secrets:
  cert.pem:
    file: .secrets/cert.pem
  key.pem:
    file: .secrets/key.pem

volumes:
    keycloak_data:
    redis_data: