name: Build React Sample Client

on:
  pull_request:
    branches:
      - main
    paths:
      - 'samples/AspNetCoreReactSample/ClientApp/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Prepare pnpm and get store path
        id: pnpm-cache
        shell: bash
        working-directory: samples/AspNetCoreReactSample/ClientApp
        run: |
          corepack enable
          corepack prepare
          echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Setup pnpm cache
        uses: actions/cache@v6
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('samples/AspNetCoreReactSample/ClientApp/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: samples/AspNetCoreReactSample/ClientApp

      - name: Build
        run: |
          pnpm lint
          pnpm build
        working-directory: samples/AspNetCoreReactSample/ClientApp
